### ISSUE TITLE
Parent object item view table filter

### ISSUE THREAD

**Issue by tmacmath** [yalelibrary/yul-dc-management#1177]
As per user request, the default state of the table filter should be changed from unfiltered to filtered (fields with null values should be hidden by default). 

Acceptance criteria: 

- [x] Table data is filtered by default (fields with null values are hidden)
- [x] Icon corresponds to functionality

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-management/pull/1183

**Comment by jpengst** [comment]
Deployed Test v2.60.5

**Comment by K8Sewell** [comment]
Defaults to filtered on Test.  Will promote to UAT.



![Image](https://user-images.githubusercontent.com/36549923/235239063-4dd07489-c145-40bf-9b18-6ce2799557fc.png)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you so much :) 

Ready to close.
